### ISSUE TITLE
Issue import watch

### ISSUE THREAD

**Issue by gaetansenn** [cmty/test-import-watch#1]
- Watch pour celui qui a créé l'issue
- Watch pour celui a créé un commentaire
- Watch pour ceux qui ont été cité (issue + commentaires)

<div align="right"><sub><em>This question is available on <a href="http://terrajs.cmty.localhost">TerraJS</a> community (<a href="http://terrajs.cmty.localhost/cmty/test-import-watch/issues/c1">#c1</a>)</em></sub></div>

**Comment by cmty-test-user1** [comment]
You should add me for watch !

**Comment by gaetansenn** [comment]
@cmty-test-user2 you should be added to

**Comment by gaetansenn** [comment]
@cmty-test-user1 you should get a notification ;)

**Comment by gaetansenn** [comment]
@cmty-test-user1  you should get a notification

**Comment by gaetansenn** [comment]
You should get a notification cmty-test-user1 ;)

**Comment by gaetansenn** [comment]
Test comment !

**Comment by cmty-test-user2** [comment]
@cmty-test-user2 je fais un test pour etre sur ;)

**Comment by gaetansenn** [comment]
@cmty-test-user2 Let's try this !
